name: Auto Release

on:
  push:
    branches:
      - main
    paths:
      - '**.json'
      - '**.yaml'
      - '**.crt'
      - '**.key'

jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 删除旧的 releases
      - name: Delete old releases
        run: |
          gh release list | grep -v Latest | cut -f 1 | xargs -I {} gh release delete {} -y || true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "RELEASE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_TAG }} \
            --title "Release ${{ env.RELEASE_TAG }}" \
            --latest \
            --notes "Automated release created at $(date +'%Y-%m-%d %H:%M:%S')" \
            *.json *.yaml *.crt *.key 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
