name: Auto Release

on:
  push:
    branches:
      - main
    paths:
      - '**.conf'
      - '**.json'
      - '**.yaml'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get current date
        id: date
        run: echo "RELEASE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create ${{ env.RELEASE_TAG }} \
            --title "Release ${{ env.RELEASE_TAG }}" \
            --notes "Automated release created at $(date +'%Y-%m-%d %H:%M:%S')" \
            *.conf *.json *.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
